import { AuditionData, audition_statuses, audition_types } from "@/types";

export const AUDITIONS: AuditionData[] = [
  {
    id: 1,
    userId: 1,
    date: new Date("01/01/23").getTime(),
    project: "Star Wars 10",
    casting: [],
    company: "Disney",
    notes: "really apprehensive about this one",
    type: "film" as audition_types,
    status: "scheduled" as audition_statuses,
    archived: false,
    createdAt: 0,
  },
  {
    id: 2,
    userId: 1,
    date: new Date("02/02/23").getTime(),
    casting: [],
    project: "Bounce",
    company: "Denardi Studios",
    notes: "Hilarious startup sitcom",
    type: "television" as audition_types,
    status: "callback" as audition_statuses,
    archived: false,
    createdAt: 0,
  },
  {
    id: 3,
    userId: 1,
    date: new Date("03/03/23").getTime(),
    project: "Foo",
    company: "Bar",
    casting: [],
    notes: "no idea",
    type: "student" as audition_types,
    status: "auditioned" as audition_statuses,
    archived: false,
    createdAt: 0,
  },
  {
    id: 4,
    userId: 1,
    date: new Date("03/02/23").getTime(),
    casting: [],
    project: "Mission Impossible 101",
    company: "Tommy Cruise",
    notes: "holy shit, another one?",
    type: "commercial" as audition_types,
    status: "booked" as audition_statuses,
    archived: false,
    createdAt: 0,
  },
].sort((a, b) => b.date - a.date);
